### PR TITLE
Use re2 for regex evaluations

### LINKED ISSUE #918: move to google/re2 for the regex engine
This is workable now we have migrated to ECS

Needs to be applied to both this repo, the flagsmith engine and the python sdk

### PR DESCRIPTION
**Pull request by matthewelwell**
Fixes #918

### CODE REVIEW

**Comment by matthewelwell** [comment]
It's worth noting that this increases the size of the image quite substantially. Need to look into whether some of these things can be done in another step of a multi step docker build perhaps? 

```
> docker inspect -f "{{ .Size }}" flagsmith/flagsmith-api:main
433365795

> docker inspect -f "{{ .Size }}" flagsmith/flagsmith-api:improvement-use-google-re2
712845968
```

**Comment by dabeeeenster** [comment]
We cant we use pyre2? It installs without needing to be compiled when I build the docker image?

**Comment by matthewelwell** [comment]
> We cant we use pyre2? It installs without needing to be compiled when I build the docker image?

You mean just `pip install pyre2` ? Does it actually _work_ though?

**Comment by dabeeeenster** [comment]
The root Dockerfile needs updating too

**Comment by dabeeeenster** [comment]
Why are we not just putting this in requirements.in?

**Comment by matthewelwell** [comment]
> Why are we not just putting this in requirements.in?

Because it doesn't install on mac.

**Review by dabeeeenster — APPROVED** [review]

**Pull request merged**
